nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"